---
# title: "Resume"
# author: "Audrey Holloman"
# date: "9/16/2018"
# output: html_document
---
# **Resume**

A PDF copy of my resume can be found [here](Holloman Resume.pdf).

### Education

* **BS in Mathematics - Physical Sciences** [Expected Graduation: May 2019]
    * Appalachian State University - Boone, NC
        * Awarded Chancellor's list and Dean's list all semesters

### Experience

#### Work

* **Mathematics and Data Analytics Tutor** - Appalachian State Learning Lab [January 2019 - Present]
    * Assist students in targeted subject areas through either individual or group tutoring. Help students understand the concepts of the math subject matter and be able to apply their understanding to any problem. Participate via ZOOM to provide video communications for students who need help after lab hours. Interact with faculty to develop tutoring material for students.

* **Engineering Instructor Assistant** - PlayWell TEKnologies [May 2018 – August 2018]
    * Co-taught sections of classes entitled Robotics in STEM and Adventures in STEM, which covered engineering fundamentals, robotics, and problem solving skills. Designed and implemented course curriculum and structure, assessed student progress, and provided guidance and assistance in comprehension of course material. Coordinated with regional managers to ensure curriculum and course material met class guidelines
        * Recognized by students for an unyielding commitment to their continual growth and learning. Received numerous letters, notes, and gifts from students for efforts on their behalf.

* **Server/Caterer/Food Preparer** - Blowing Rock Country Club [May 2017 – October 2017]
    * Delivered friendly and efficient service to ensure a pleasant dining experience for all guests suggesting menu items and suggesting specialty drinks according to corporate specifications. Learned the menu for each function. Served and explained the major ingredients and preparation methods for each item to be served. Fostered repeat business and a clientele of regular patrons. Trained new servers on menu knowledge and steps of quality service.
        * Always top 3 in server excellence chart and had many positive customer surveys. Asked to contribute to being apart of the managing staff for the following summer.

* **Caterer** - Rocky Top Catering [November 2016 - January 2017]
    * Provided teamwork to all teammates and promoted a sense of urgency for the guests and team members. Performed side work. Communicated with support crew and management. Monitored and maintained cleanliness, sanitation, and organizatin of the management team. Knowledge of how to set up and break down both a buffet and seated meal functions.

#### Computer Training

##### Efficient in:

* RStudio
* Microsoft Excel
* Maplesoft
* Python
* Github
* SQL
* Gephi
* MATLAB
* Microsoft PowerPoint
* Insight Maker
* Microsoft Word
* LaTeX

### Organization Memberships

* **Chi Omega Sorority** [September 2015 – Present]
    * Provides personal integrity, friendship, leadership opportunities, service to others, intellectual pursuits, community & campus involvement, and personal & career development

* **National Society of Leadership and Success** [September 2017 – Present]
    * Provides leadership skills, encourages the greater community by organizing action to the better world, and brings together success oriented individuals to help one another succeed

* **Math Club** [September 2015 – Present]
    * Raises money for students to attend Mathematical Contest in Modeling through small events like bake sales in the math building

* **Panda (Physics and Astronomy) Club** [January 2017 – Present]
    * Builds a community of students and profesionals interested in physics by educating the community & peers about physics/astronomy. Raise money by selling coffee to students in the physics building so we can host/manage different outreach events that we participate in.
  
### Additional Involvement

* Will attend DataFest 2019 data analysis competition at Duke University

* **Hospitality House of Northwest North Carolina** [2015 - Present]
    * Prepared and cooked meals for Chi Omega - Pi Kappa chapter's local philanthropy 5 times a semester
    
* **Chi Omega - Blue Tie Gala** [2018]
    * Helped Organize and manage an auction where all proceeds went to Chi Omega's national philanthropy, Make-A-Wish
        * Raised over $15,000

* **Tom More 5K** [2017]
    * Volunteered and participated in a run that raised money for Huntington's Disease Society of America
        * Raised over $11,000

* **Math Tutor - Wade Edwards** Learning Lab [2014 -2015]
    * Mentored and helped students with lower-level math topics

### Contact

155 A Clement Street - Boone, NC 28607 - hollomanma@appstate.edu - 919-436-0168